# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_label.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1680, 1005)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_Centre = QtWidgets.QVBoxLayout()
        self.verticalLayout_Centre.setObjectName("verticalLayout_Centre")
        self.comboBox_txtsdyFiles = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_txtsdyFiles.setEnabled(False)
        self.comboBox_txtsdyFiles.setObjectName("comboBox_txtsdyFiles")
        self.comboBox_txtsdyFiles.addItem("")
        self.verticalLayout_Centre.addWidget(self.comboBox_txtsdyFiles)
        self.checkBox_Pa = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Pa.setEnabled(False)
        self.checkBox_Pa.setChecked(True)
        self.checkBox_Pa.setObjectName("checkBox_Pa")
        self.verticalLayout_Centre.addWidget(self.checkBox_Pa)
        self.graphicsView_ = PlotWidget(self.centralwidget)
        self.graphicsView_.setObjectName("graphicsView_")
        self.verticalLayout_Centre.addWidget(self.graphicsView_)
        self.gridLayout.addLayout(self.verticalLayout_Centre, 0, 1, 1, 1)
        self.verticalLayout_Left = QtWidgets.QVBoxLayout()
        self.verticalLayout_Left.setObjectName("verticalLayout_Left")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_StudyData = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_StudyData.setFont(font)
        self.label_StudyData.setObjectName("label_StudyData")
        self.verticalLayout.addWidget(self.label_StudyData)
        self.label_PatientID = QtWidgets.QLabel(self.centralwidget)
        self.label_PatientID.setObjectName("label_PatientID")
        self.verticalLayout.addWidget(self.label_PatientID)
        self.label_StudyDate = QtWidgets.QLabel(self.centralwidget)
        self.label_StudyDate.setObjectName("label_StudyDate")
        self.verticalLayout.addWidget(self.label_StudyDate)
        self.label_ExportDate = QtWidgets.QLabel(self.centralwidget)
        self.label_ExportDate.setObjectName("label_ExportDate")
        self.verticalLayout.addWidget(self.label_ExportDate)
        self.verticalLayout_Left.addLayout(self.verticalLayout)
        self.verticalLayout_Buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_Buttons.setObjectName("verticalLayout_Buttons")
        self.label_Buttons = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_Buttons.setFont(font)
        self.label_Buttons.setObjectName("label_Buttons")
        self.verticalLayout_Buttons.addWidget(self.label_Buttons, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_Left.addLayout(self.verticalLayout_Buttons)
        self.verticalLayout_Info = QtWidgets.QVBoxLayout()
        self.verticalLayout_Info.setObjectName("verticalLayout_Info")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_Info.addWidget(self.textBrowser)
        self.verticalLayout_Left.addLayout(self.verticalLayout_Info)
        self.gridLayout.addLayout(self.verticalLayout_Left, 0, 0, 1, 1)
        self.verticalLayout_Results = QtWidgets.QVBoxLayout()
        self.verticalLayout_Results.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_Results.setObjectName("verticalLayout_Results")
        self.verticalLayout_Pressures = QtWidgets.QVBoxLayout()
        self.verticalLayout_Pressures.setObjectName("verticalLayout_Pressures")
        self.label_Pressures = QtWidgets.QLabel(self.centralwidget)
        self.label_Pressures.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Pressures.setObjectName("label_Pressures")
        self.verticalLayout_Pressures.addWidget(self.label_Pressures)
        self.tableWidget_Pressures = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Pressures.sizePolicy().hasHeightForWidth())
        self.tableWidget_Pressures.setSizePolicy(sizePolicy)
        self.tableWidget_Pressures.setObjectName("tableWidget_Pressures")
        self.tableWidget_Pressures.setColumnCount(0)
        self.tableWidget_Pressures.setRowCount(0)
        self.verticalLayout_Pressures.addWidget(self.tableWidget_Pressures)
        self.verticalLayout_Results.addLayout(self.verticalLayout_Pressures)
        self.verticalLayout_PressureRatios = QtWidgets.QVBoxLayout()
        self.verticalLayout_PressureRatios.setObjectName("verticalLayout_PressureRatios")
        self.label_PressureRatios = QtWidgets.QLabel(self.centralwidget)
        self.label_PressureRatios.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PressureRatios.setObjectName("label_PressureRatios")
        self.verticalLayout_PressureRatios.addWidget(self.label_PressureRatios)
        self.tableWidget_PressureRatios = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_PressureRatios.sizePolicy().hasHeightForWidth())
        self.tableWidget_PressureRatios.setSizePolicy(sizePolicy)
        self.tableWidget_PressureRatios.setObjectName("tableWidget_PressureRatios")
        self.tableWidget_PressureRatios.setColumnCount(0)
        self.tableWidget_PressureRatios.setRowCount(0)
        self.verticalLayout_PressureRatios.addWidget(self.tableWidget_PressureRatios)
        self.verticalLayout_Results.addLayout(self.verticalLayout_PressureRatios)
        self.verticalLayout_Flows = QtWidgets.QVBoxLayout()
        self.verticalLayout_Flows.setObjectName("verticalLayout_Flows")
        self.label_Flows = QtWidgets.QLabel(self.centralwidget)
        self.label_Flows.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Flows.setObjectName("label_Flows")
        self.verticalLayout_Flows.addWidget(self.label_Flows)
        self.tableWidget_Flows = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Flows.sizePolicy().hasHeightForWidth())
        self.tableWidget_Flows.setSizePolicy(sizePolicy)
        self.tableWidget_Flows.setObjectName("tableWidget_Flows")
        self.tableWidget_Flows.setColumnCount(0)
        self.tableWidget_Flows.setRowCount(0)
        self.verticalLayout_Flows.addWidget(self.tableWidget_Flows)
        self.verticalLayout_Results.addLayout(self.verticalLayout_Flows)
        self.verticalLayout_FlowRatios = QtWidgets.QVBoxLayout()
        self.verticalLayout_FlowRatios.setObjectName("verticalLayout_FlowRatios")
        self.label_FlowRatios = QtWidgets.QLabel(self.centralwidget)
        self.label_FlowRatios.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FlowRatios.setObjectName("label_FlowRatios")
        self.verticalLayout_FlowRatios.addWidget(self.label_FlowRatios)
        self.tableWidget_FlowRatios = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_FlowRatios.sizePolicy().hasHeightForWidth())
        self.tableWidget_FlowRatios.setSizePolicy(sizePolicy)
        self.tableWidget_FlowRatios.setObjectName("tableWidget_FlowRatios")
        self.tableWidget_FlowRatios.setColumnCount(0)
        self.tableWidget_FlowRatios.setRowCount(0)
        self.verticalLayout_FlowRatios.addWidget(self.tableWidget_FlowRatios)
        self.verticalLayout_Results.addLayout(self.verticalLayout_FlowRatios)
        self.verticalLayout_Resistances = QtWidgets.QVBoxLayout()
        self.verticalLayout_Resistances.setObjectName("verticalLayout_Resistances")
        self.label_Resistances = QtWidgets.QLabel(self.centralwidget)
        self.label_Resistances.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Resistances.setObjectName("label_Resistances")
        self.verticalLayout_Resistances.addWidget(self.label_Resistances)
        self.tableWidget_Resistances = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Resistances.sizePolicy().hasHeightForWidth())
        self.tableWidget_Resistances.setSizePolicy(sizePolicy)
        self.tableWidget_Resistances.setObjectName("tableWidget_Resistances")
        self.tableWidget_Resistances.setColumnCount(0)
        self.tableWidget_Resistances.setRowCount(0)
        self.verticalLayout_Resistances.addWidget(self.tableWidget_Resistances)
        self.verticalLayout_Results.addLayout(self.verticalLayout_Resistances)
        self.horizontalLayout_Export = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Export.setObjectName("horizontalLayout_Export")
        self.pushButton_ExportStudy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ExportStudy.setStyleSheet("background-color: \'green\'")
        self.pushButton_ExportStudy.setObjectName("pushButton_ExportStudy")
        self.horizontalLayout_Export.addWidget(self.pushButton_ExportStudy)
        self.pushButton_ExportAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ExportAll.setStyleSheet("background-color: \'red\'")
        self.pushButton_ExportAll.setObjectName("pushButton_ExportAll")
        self.horizontalLayout_Export.addWidget(self.pushButton_ExportAll)
        self.verticalLayout_Results.addLayout(self.horizontalLayout_Export)
        self.gridLayout.addLayout(self.verticalLayout_Results, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 8)
        self.gridLayout.setColumnStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_study = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../BARD/ui/icons/Patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_study.setIcon(icon)
        self.actionLoad_study.setObjectName("actionLoad_study")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../BARD/ui/icons/About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionLoad_study)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CoPhyPy"))
        self.comboBox_txtsdyFiles.setCurrentText(_translate("MainWindow", "Please select a file"))
        self.comboBox_txtsdyFiles.setItemText(0, _translate("MainWindow", "Please select a file"))
        self.checkBox_Pa.setText(_translate("MainWindow", "Use Physiology Channel for Pa (SDY files only)"))
        self.label_StudyData.setText(_translate("MainWindow", "Study Data"))
        self.label_PatientID.setText(_translate("MainWindow", "Patient ID:"))
        self.label_StudyDate.setText(_translate("MainWindow", "Study Date:"))
        self.label_ExportDate.setText(_translate("MainWindow", "Export Date:"))
        self.label_Buttons.setText(_translate("MainWindow", "Ranges"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Information</span></p></body></html>"))
        self.label_Pressures.setText(_translate("MainWindow", "Pressures"))
        self.label_PressureRatios.setText(_translate("MainWindow", "Pressure Ratios"))
        self.label_Flows.setText(_translate("MainWindow", "Flows"))
        self.label_FlowRatios.setText(_translate("MainWindow", "Flow Ratios"))
        self.label_Resistances.setText(_translate("MainWindow", "Resistances"))
        self.pushButton_ExportStudy.setText(_translate("MainWindow", "Export\n"
"Study"))
        self.pushButton_ExportAll.setText(_translate("MainWindow", "Export ALL\n"
"Studies in Folder"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_study.setText(_translate("MainWindow", "Load patient"))
        self.actionLoad_study.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

from pyqtgraph import PlotWidget
